KontaktiMVC/Controllers/BrojController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KontaktiMVC;

namespace KontaktiMVC.Controllers
{
    public class BrojController : Controller
    {
        private KontaktiEntities db = new KontaktiEntities();

        // GET: Broj/Create
        public ActionResult Create()
        {
            ViewBag.id_osoba = new SelectList(db.Osoba, "id", "ime");
            return View();
        }

        // POST: Broj/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "broj1,tip,opis,id_osoba")] Broj broj)
        {
            if (ModelState.IsValid)
            {
                db.Broj.Add(broj);
                db.SaveChanges();
                return RedirectToAction("Index", "Osoba");
            }

            ViewBag.id_osoba = new SelectList(db.Osoba, "id", "ime", broj.id_osoba);
            return View(broj);
        }

        // GET: Broj/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Broj broj = db.Broj.Find(id);
            if (broj == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_osoba = new SelectList(db.Osoba, "id", "ime", broj.id_osoba);
            return View(broj);
        }

        // POST: Broj/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "broj1,tip,opis,id_osoba")] Broj broj)
        {
            if (ModelState.IsValid)
            {
                db.Entry(broj).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Osoba");
            }
            ViewBag.id_osoba = new SelectList(db.Osoba, "id", "ime", broj.id_osoba);
            return View(broj);
        }

        // GET: Broj/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Broj broj = db.Broj.Find(id);
            if (broj == null)
            {
                return HttpNotFound();
            }
            return View(broj);
        }

        // POST: Broj/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Broj broj = db.Broj.Find(id);
            db.Broj.Remove(broj);
            db.SaveChanges();
            return RedirectToAction("Index","Osoba");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KontaktiMVC/Controllers/OsobaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KontaktiMVC;
using PagedList;

namespace KontaktiMVC.Controllers
{
    public class OsobaController : Controller
    {
        private KontaktiEntities db = new KontaktiEntities();

        // GET: Osoba
        public ViewResult Index(string currentFilter, string searchString, int? page)
        {
            if (searchString!=null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.currentFilter = searchString;

            var listaOsoba = from o in db.Osoba
                             select o;

            foreach (var osoba in listaOsoba)
            {
                foreach (var broj in osoba.Broj.ToList())
                {
                    osoba.BrojeviText += "," + broj.broj1.ToString();
                }
                if (string.IsNullOrWhiteSpace(osoba.BrojeviText)) osoba.BrojeviText = "Nema brojeva.";
                else osoba.BrojeviText = osoba.BrojeviText.Substring(1);
            }
            
            if (!string.IsNullOrEmpty(searchString))
            {
                var list = listaOsoba.ToList().Where(l => l.ime.Contains(searchString) || l.prezime.Contains(searchString) ||
                                             l.BrojeviText.Contains(searchString));
                listaOsoba = list.AsQueryable();
            }

            int pageSize = 8;
            int pageNumber = (page ?? 1);
            listaOsoba = listaOsoba.OrderBy(l => l.prezime);
            return View(listaOsoba.ToPagedList(pageNumber, pageSize));
        }

        // GET: Osoba/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Osoba osoba = db.Osoba.Find(id);
            if (osoba == null)
            {
                return HttpNotFound();
            }
            return View(osoba);
        }

        // GET: Osoba/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Osoba/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,ime,prezime,grad,opis,slika")] Osoba osoba)
        {
            if (ModelState.IsValid)
            {
                db.Osoba.Add(osoba);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(osoba);
        }

        // GET: Osoba/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Osoba osoba = db.Osoba.Find(id);
            if (osoba == null)
            {
                return HttpNotFound();
            }
            return View(osoba);
        }

        // POST: Osoba/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,ime,prezime,grad,opis,slika")] Osoba osoba)
        {
            if (ModelState.IsValid)
            {
                db.Entry(osoba).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(osoba);
        }

        // GET: Osoba/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Osoba osoba = db.Osoba.Find(id);
            if (osoba == null)
            {
                return HttpNotFound();
            }
            return View(osoba);
        }

        // POST: Osoba/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Osoba osoba = db.Osoba.Find(id);
            db.Osoba.Remove(osoba);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KontaktiMVC/Views/Broj/Create.cshtml
@model KontaktiMVC.Broj

@{
    ViewBag.Title = "Create";
}

<h2>Novi broj</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <div class="control-label col-md-2">Telefonski broj</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.broj1, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.broj1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Tip</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.tip, new { htmlAttributes = new { @class = "form-control" }, @required = "required" })
                @Html.ValidationMessageFor(model => model.tip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Opis</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.opis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.opis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Kontakt</div>
            <div class="col-md-10">
                @Html.DropDownList("id_osoba", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_osoba, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spremi" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Povratak", "Index", "Osoba")
</div>

KontaktiMVC/Views/Broj/Delete.cshtml
@model KontaktiMVC.Broj

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Broj</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.tip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.opis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.opis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Osoba.ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Osoba.ime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Izbriši" class="btn btn-default" /> |
            @Html.ActionLink("Povratak", "Index")
        </div>
    }
</div>

KontaktiMVC/Views/Broj/Edit.cshtml
@model KontaktiMVC.Broj

@{
    ViewBag.Title = "Edit";
}

<h2>Uredi broj</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <div class="control-label col-md-2">Telefonski broj</div>
            @Html.EditorFor(model => model.broj1, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
            @Html.ValidationMessageFor(model => model.broj1, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Tip</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.tip, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.tip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Opis</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.opis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.opis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Kontakt</div>
            <div class="col-md-10">
                @Html.DropDownList("id_osoba", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_osoba, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spremi" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Povratak", "Index", "Osoba")
</div>

KontaktiMVC/Views/Osoba/Create.cshtml
@model KontaktiMVC.Osoba

@{
    ViewBag.Title = "Create";
}

<h2>Novi kontakt</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="control-label col-md-2">Ime</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.ime, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.ime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Prezime</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.prezime, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.prezime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Grad</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.grad, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.grad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Opis</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.opis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.opis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Slika</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.slika, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.slika, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spremi" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Povratak", "Index")
</div>

KontaktiMVC/Views/Osoba/Delete.cshtml
@model KontaktiMVC.Osoba

@{
    ViewBag.Title = "Delete";
}

<style>
    img {
        max-height:100px;
        max-width:100px;
    }
</style>

<h2>Brisanje kontakta</h2>

<h3>Jeste li sigurni?</h3>
<div>
    <h4>Kontakt</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt> </dt>
        <dd>
            <img src="@Url.Content(Model.slika)" alt="Slika nedostupna"/>
        </dd>

        <dt>
            Ime
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ime)
        </dd>

        <dt>
            Prezime
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prezime)
        </dd>

        <dt>
            Grad
        </dt>

        <dd>
            @Html.DisplayFor(model => model.grad)
        </dd>

        <dt>
            Opis
        </dt>

        <dd>
            @Html.DisplayFor(model => model.opis)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Izbriši" class="btn btn-default" /> |
            @Html.ActionLink("Povratak", "Index")
        </div>
    }
</div>

KontaktiMVC/Views/Osoba/Details.cshtml
@model KontaktiMVC.Osoba

@{
    ViewBag.Title = "Details";
}

<style>
    img {
        max-height: 200px;
        max-width: 200px;
    }
</style>

<h2>Podaci o kontaktu</h2>

<div>
    <hr />

    <dl class="dl-horizontal">
        <dt> </dt>
        <dd>
            <img src="@Url.Content(Model.slika)" alt="Slika nedostupna"/>
        </dd>
        <dt>
            Ime
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ime)
        </dd>

        <dt>
            Prezime
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prezime)
        </dd>

        <dt>
            Grad
        </dt>

        <dd>
            @Html.DisplayFor(model => model.grad)
        </dd>

        <dt>
           Opis
        </dt>

        <dd>
            @Html.DisplayFor(model => model.opis)
        </dd>

        <dt>
            Telefonski brojevi
        </dt>
        <dd>
            <p>@Html.ActionLink("Dodaj broj" , "Create", "Broj",null,null)</p>
            <table class="table">
                <tr>
                    <th>Broj</th>
                    <th>Tip</th>
                    <th>Opis</th>
                    <th></th>
                </tr>
                @foreach (var item in Model.Broj)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.broj1)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.tip)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.opis)
                        </td>
                        <td>
                            @Html.ActionLink("Uredi","Edit","Broj", new { id = item.broj1 }, null) | 
                            @Html.ActionLink("Izbriši", "Delete", "Broj", new {id = item.broj1}, null)
                        </td>
                    </tr>
                }
            </table>
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Uredi", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Povratak", "Index")
</p>

KontaktiMVC/Views/Osoba/Edit.cshtml
@model KontaktiMVC.Osoba

@{
    ViewBag.Title = "Edit";
}

<h2>Uredi kontakt</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            <div class="control-label col-md-2">Ime</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.ime, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.ime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Prezime</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.prezime, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.prezime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Grad</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.grad, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.grad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Opis</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.opis, new { htmlAttributes = new { @class = "form-control" }})
                @Html.ValidationMessageFor(model => model.opis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">Slika</div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.slika, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.slika, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spremi" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Povratak", "Index")
</div>

KontaktiMVC/Views/Osoba/Index.cshtml
@model PagedList.IPagedList<KontaktiMVC.Osoba>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css"/>

@{
    ViewBag.Title = "Index";
}

<h2>Kontakti</h2>

<p>
    @Html.ActionLink("Dodaj kontakt", "Create")
</p>

@using (Html.BeginForm())
{
    <p>
        Pretraži prema imenu ili broju: @Html.TextBox("SearchString", ViewBag.CurrentFilte as string)
        <input type="submit" value="Traži" />
    </p>
}

<table class="table">
    <tr>
        <th>
            Ime
        </th>
        <th>
            Prezime
        </th>
        <th>
            Grad
        </th>
        <th>
            Telefonski brojevi
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.prezime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.grad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BrojeviText)
            </td>
            <td>
                @Html.ActionLink("Uredi", "Edit", new { id = item.id }) |
                @Html.ActionLink("Detalji", "Details", new { id = item.id }) |
                @Html.ActionLink("Izbriši", "Delete", new { id = item.id })
            </td>
        </tr>
        }

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page, currentFilte = ViewBag.CurrentFilter}))

KontaktiMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Kontakti</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>Last refreshed: @DateTime.Now</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>